databases:
  - name: cutiedogs_DB
    databaseName: cutiedogs_db
    user: cutiedogs
    region: singapore

services:
  - type: web
    name: cutiedogs
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cutiedogs_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

